name: GRposenet
type: GR

detector: configs/detector/detector_train.yaml
selector: configs/selector/selector_train.yaml
refiner:  configs/refiner/refiner_train.yaml
ref_resolution: 128   # reference image resolution

#ref_view_num: 16      # view number used in selection
ref_view_num: 32      # view number used in selection
#det_ref_view_num: 16  # view number used in detection
det_ref_view_num: 32  # view number used in detection


refine_iter: 3        # refinement iteration number
